2023-10-17 23:24:51.549 - DEBUG - Using proactor: IocpProactor
2023-10-17 23:24:51.572 - INFO - Started server process [7428]
2023-10-17 23:24:51.573 - INFO - Waiting for application startup.
2023-10-17 23:24:51.574 - INFO - Application startup complete.
2023-10-17 23:24:51.576 - INFO - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_start with no data
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_name with data[0:10]
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_data with data[11:19]
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_end with no data
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_start with no data
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_name with data[20:28]
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_data with data[29:36]
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_end with no data
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_start with no data
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_name with data[37:45]
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_data with data[46:50]
2023-10-17 23:25:04.153 - DEBUG - Calling on_field_end with no data
2023-10-17 23:25:04.154 - DEBUG - Calling on_end with no data
2023-10-17 23:25:04.247 - INFO - select pg_catalog.version()
2023-10-17 23:25:04.248 - INFO - [raw sql] ()
2023-10-17 23:25:04.254 - INFO - select current_schema()
2023-10-17 23:25:04.254 - INFO - [raw sql] ()
2023-10-17 23:25:04.261 - INFO - show standard_conforming_strings
2023-10-17 23:25:04.262 - INFO - [raw sql] ()
2023-10-17 23:25:04.269 - INFO - BEGIN (implicit)
2023-10-17 23:25:04.276 - INFO - SELECT users.id, users.username, users.hashed_password, users.is_active 
FROM users 
WHERE users.username = %s
2023-10-17 23:25:04.277 - INFO - [generated in 0.00086s] ('sudakov',)
2023-10-17 23:25:04.285 - DEBUG - detected 'bcrypt' backend, version '4.0.1'
2023-10-17 23:25:04.286 - DEBUG - 'bcrypt' backend lacks $2$ support, enabling workaround
2023-10-17 23:25:04.589 - INFO - ROLLBACK
2023-10-17 23:25:16.119 - DEBUG - Calling on_part_begin with no data
2023-10-17 23:25:16.119 - DEBUG - Calling on_header_field with data[42:61]
2023-10-17 23:25:16.119 - DEBUG - Calling on_header_value with data[63:104]
2023-10-17 23:25:16.119 - DEBUG - Calling on_header_end with no data
2023-10-17 23:25:16.119 - DEBUG - Calling on_header_field with data[106:118]
2023-10-17 23:25:16.119 - DEBUG - Calling on_header_value with data[120:133]
2023-10-17 23:25:16.119 - DEBUG - Calling on_header_end with no data
2023-10-17 23:25:16.119 - DEBUG - Calling on_headers_finished with no data
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[137:574]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[0:2]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[576:1354]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[0:2]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[1356:1442]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[0:2]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[1444:1467]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_data with data[0:2]
2023-10-17 23:25:16.120 - DEBUG - Calling on_part_end with no data
2023-10-17 23:25:16.120 - DEBUG - Calling on_end with no data
2023-10-17 23:25:16.121 - INFO - BEGIN (implicit)
2023-10-17 23:25:16.122 - INFO - SELECT users.id, users.username, users.hashed_password, users.is_active 
FROM users 
WHERE users.username = %s
2023-10-17 23:25:16.123 - INFO - [cached since 11.85s ago] ('sudakov',)
2023-10-17 23:25:16.129 - INFO - ROLLBACK
2023-10-17 23:25:16.134 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Dev\async-python-sprint-5_\src\api\v1\files.py", line 49, in upload_file
    file_upload: dict = await files_crud.create(db=db, file=file, user=user, path=subdir)
  File "C:\Dev\async-python-sprint-5_\src\services\files.py", line 43, in create
    written_bytes = await write_file(path_dir=directory_path_, file=file)
  File "C:\Dev\async-python-sprint-5_\src\tools\files.py", line 24, in write_file
    async with aiofiles.open(Path(path_dir, file.filename), "wb") as file_:
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\site-packages\aiofiles\threadpool\__init__.py", line 94, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "C:\Users\API\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
OSError: [Errno 22] Invalid argument: 'C:\\Dev\\async-python-sprint-5_\\src\\files_storage\\<built-in function id>_sudakov\\bot.py'
2023-10-17 23:28:40.814 - INFO - Shutting down
2023-10-17 23:28:40.925 - INFO - Waiting for application shutdown.
2023-10-17 23:28:40.926 - INFO - Application shutdown complete.
2023-10-17 23:28:40.927 - INFO - Finished server process [7428]
